[workspace]
members = [
	"bytereader",
	"swai-parser"
]


[package]
name = "swai"
version = "0.0.1"
edition = "2021"
description = "A Simple WebAssembly Interpreter"

[dependencies]
nom = "7.1.3"
nom-leb128 = "0.2.0"
swai-parser = { path = "./swai-parser" }
